### ISSUE TITLE
Profiler endpoint configuration

### ISSUE THREAD

**Issue by mcrumm** [mcrumm/phoenix_profiler#38]
This project has two parts– the profiler and the web debug toolbar. We want to allow configuration so the profiler can be invoked without rendering the toolbar.

The configuration lives on the Endpoint at `:phoenix_profiler`. I am thinking we add the following:

```elixir
config :my_app, MyAppWeb.Endpoint,
  phoenix_profiler: boolean() | [ # default is false (so it can be explicitly enabled per env)
    enabled: boolean(), # default is true
    exclude_patterns: list(Regex.t()), # default is []
    link_base_path: String.t(), # default is "/dashboard/_profiler"
    reduced_motion: boolean() # default is false
    web_debug_toolbar: boolean() # default is true
  ]
```

Note the toolbar is dependent on the profiler, so setting `phoenix_profiler: [enabled: false, web_debug_toolbar: true]` must _not_ render the toolbar.

**Comment by leandrocp** [comment]
> reduced_motion

That config is related to the web toolbar only, right? What if we add it inside the `web_debug_toolbar`? And consequently add a `enable` key inside it so the toolbar config has room to others keys as needed too.

> Note the toolbar is dependent on the profiler, so setting phoenix_profiler: [enabled: false, web_debug_toolbar: true] must not render the toolbar

A IO.warn would be handy to avoid confusion :)

> enabled x enable

An imperative "enable" sounds better for me, but just a nitpicking here.
