### ISSUE TITLE
Route information is shown only briefly, but then is replaced with `route_not_found`

### ISSUE THREAD

**Issue by iautom8things** [mcrumm/phoenix_profiler#56]
This happens on my Live+Dead view pages, but not the LiveDashboard.  So I'm open to the idea that there's something wrong with my project. 

Here's what we see:
![example](https://p171.p4.n0.cdn.getcloudapp.com/items/nOu9Reoo/049a6d80-be5a-415a-a571-853cf4750612.gif?source=viewer&v=ece0eb18cc5438777d22fbd078f5464a)

**Comment by mcrumm** [comment]
Fyi, LiveDashboard only gets the "dead" toolbar, so as a comparison it is only helpful to a point. :)

From the screen capture, the issue seems to occur on connected mount, so either the toolbar can't find the profile, or there may be something wrong with the live navigation check. 🤔

Is the LiveView for the `@portal` route mounted at the router?

**Comment by iautom8things** [comment]
This is actually a deadview page, which is why it's confusing that we're seeing this happen here:

```elixir
 resources("/portals", PortalController, only: [:index, :show, :create])
```

But this page does have a few uses of `live_render`:

```elixir
<%= live_render @conn,  #... %>
```

Is that the cause?

We do have a more traditional live views that are mounted at the router, and those experience the same issue.

```elixir
    live_session :config_search do
      live "/config_search", ConfigSearchLive.Index, :index
    end
```

**Comment by mcrumm** [comment]
> But this page does have a few uses of live_render

That might be it! :) Thank you for the report, I will do some testing around that use case!

**Comment by iautom8things** [comment]
Ah ... know what?  So our navbar has a dropdown that also uses a `live_render` for a way to search+quick find other portals.  So that explains why it also affects the live view mounted in the router.

Thank you.  I do want to spend some time to become a little more intimate with the project.
