### ISSUE TITLE
PhoenixProfiler seems to break `attach_hook`

### ISSUE THREAD

**Issue by miguel-s** [mcrumm/phoenix_profiler#61]
Hi @mcrumm!

Thanks for publishing this awesome profiler!

### Issue

After following the setup instructions for the Phoenix Profiler my app started raising this exception:

> ** (exit) an exception was raised:
    ** (RuntimeError) cannot attach hook with id :active_tab on :handle_params because the view was not mounted at the router with the live/3 macro

I have a simple on_mount hook in `MyAppWeb.Nav` that handles setting a few assigns:

```elixir
def on_mount(:default, _params, _session, socket) do
  {:cont,
   socket
   |> attach_hook(:active_tab, :handle_params, &handle_active_tab_params/3)
   |> attach_hook(:active_date, :handle_params, &handle_active_date_params/3)}
end
```

Which is used in the router:

```elixir
live_session :authenticated,
      on_mount: [{MyAppWeb.UserAuth, :ensure_authenticated}, MyAppWeb.Nav] do
  # routes...
end
```

Removing the Phoenix Profiler dev config or removing the calls to `attach_hook` will get rid of the error, but obviously either the profiler or the assigns will be removed as well.

**Comment by miguel-s** [comment]
Thanks @leandrocp your workaround worked!

**Comment by iautom8things** [comment]
> That's a know issue that is related to phoenix_live_view

Just curious -- Is there a related discussion regarding this anywhere?

**Comment by mcrumm** [comment]
@iautom8things Leandro and I had a realtime discussion about whether or not to propose a way to make lifecycle hooks conditional on LiveView modules not mounted at the router. It may be possible to pass an option to `live_render/3` to ignore the hooks, but I am not sure.
