### ISSUE TITLE
API for Extensions

### ISSUE THREAD

**Issue by florianb** [mcrumm/phoenix_profiler#63]
Hi - thank you very much for this plugin. It is very useful for debugging purposes.

I'd like to ask if you could think of a way to provide an extension API? 

What i'd like to do is to add a impersonation-control to the profiler in our applications to quickly switch the current user/account. Probably this tool is entirely the wrong place to put such a functionality in. Or you already provide some extension points i am not aware of.

What would you think?

I am happy to lend a helping hand to put a PR up – Florian

**Comment by mcrumm** [comment]
Hi @florianb– I'm terribly sorry for the delay! The profiler/toolbar is still very new so we are not quite ready for a plugin/extension API yet. I do have some thoughts on how to structure such things– it will probably resemble a bit [LiveDashboard PageBuilder](https://hexdocs.pm/phoenix_live_dashboard/Phoenix.LiveDashboard.PageBuilder.html).

I am going to close this for now but I will try to reach out when we are ready to tackle this, thanks!
