### ISSUE TITLE
Liveview 0.18.0?

### ISSUE THREAD

**Issue by aselder** [mcrumm/phoenix_profiler#64]
Is it possible to support Liveview 0.18.0?

**Comment by mcrumm** [comment]
Yes, very soon!

**Comment by aselder** [comment]
> Yes, very soon!

🎉  Woohoo!!!!

**Comment by mcrumm** [comment]
@aselder The `mc-lv018` branch supports LiveView 0.18.0– if you are able to try it please let me know how it goes! :)

**Comment by nickkaltner** [comment]
i could only find main and mc-endpoint branches otherwise i would have tested :)

**Comment by mcrumm** [comment]
It has already been merged :)
v0.2.0 of the profiler supports LiveView 0.18+

**Comment by nickkaltner** [comment]
what a rookie! thank you :)
